### ISSUE TITLE
Refer to 'Readme Driven Development'

### ISSUE THREAD

**Issue by Miserlou** [noffle/art-of-readme#16]
This might be out of scope, but it could be interesting to mention why GitHub has the README files as the default "homepage" of any repo seems to be as a result of Tim Preston Werner's influential essay, _[Readme Driven Development](http://tom.preston-werner.com/2010/08/23/readme-driven-development.html)_ (which I myself am a staunch adherent to.)

Cool project!

**Comment by RichardLitt** [comment]
I don't think this is out of scope. It should be referenced. Super useful.

**Comment by noffle** [comment]
Thank you for sharing this, @Miserlou! :star2: 

> but it could be interesting to mention why GitHub has the README files as the default "homepage" of any repo seems to be as a result of Tim Preston Werner's influential essay, Readme Driven Development

That's very interesting -- I didn't know that! Do you have a source, if I wanted to cite it?

Overall I think that RDD sounds like a really neat idea. I haven't tried this approach personally, so I think I'd want to hold off endorsing it until I had the chance to do so and reflect on it. I'll keep this in mind and try it out for the next module I write!

**Comment by Miserlou** [comment]
I don't have a source on hand, but Tim Preston Warner is the founder of GitHub! Previously, no other code host would do this, or have a "start project with README" button. Now it seems like they all do. Zach, another GH co-founder, [has a similar essay](https://zachholman.com/posts/documentation/).

**Comment by noffle** [comment]
I added a new "Further Reading" section today, and am linking to this.
