### ISSUE TITLE
Consider abstracting npm-specific language

### ISSUE THREAD

**Issue by thenickcox** [noffle/art-of-readme#21]
This is a really fantastic document, and I think it has some practical suggestions for developers outside of the Node community. It feels like it would be even more valuable to make it language and ecosystem agnostic.

If this is a direction you'd consider going, would you accept some PR's in that direction?

**Comment by noffle** [comment]
Hi @thenickcox! Yes, I think that is a 100% excellent idea. To be honest, I wrote this article with a very tiny audience in mind (some friends and colleagues), and had no idea it would find its way in front of so many eyeballs! Making the document more accessible to folks outside of Node seems very much in line with the spirit of the article. :+1:   Please feel free to tackle this!

**Comment by thenickcox** [comment]
Hi, @noffle. Apologies for the delay. I've been quite sick the past two weeks; I'm only just now coming out of it.

I've been thinking about this because I submitted a talk to [OSCON](http://conferences.oreilly.com/oscon/oscon-tx) on documentation!

Let's discuss implementation for this. As I see it, this could be implemented either by including examples _outside_ of the Node community, or making the examples more abstract and conceptual, and excluding the particulars of Node. 

As I write that, it seems like the first option might be the most sound. Would you agree?

If so, are there other examples of great READMEs that you can think of? I'll go through some of my favorite Ruby projects; I have less experience outside of the Ruby and JavaScript communities, although I do dabble a bit in Go, and those packages sometimes can be quite small and in line with the npm module philosophy in that regard.

Thoughts?

**Comment by noffle** [comment]
@thenickcox yes! Yes to it all. *Yes!* to your talk on documentation,
and *Yes!* to more examples outside of Node. It will be interesting to
see how well my guidelines (which are admittedly very Node-centric) hold
up to the diversity of other ecosystems.
