### ISSUE TITLE
i18n Folder

### ISSUE THREAD

**Issue by lennonjesus** [noffle/art-of-readme#26]
My folder organization suggestion:

```
/README.md
/i18n/README-zh.md
/i18n/README-ru.md
/i18n/README-pt-BR.md
/i18n/README-cool-translation.md
```

**Comment by noffle** [comment]
Hey @lennonjesus, is there advantage doing it this way compared to just keeping them in the root directory?

**Comment by lennonjesus** [comment]
Only for clarify the i18n intention and to reduce the amount of files in the main directory.

I think we'll have many translations.

**Comment by noffle** [comment]
Good call re: reducing main directory size. That'll keep the article content right at the top. :+1: 

I'll do this if the translations keep on coming in!

**Comment by Artoria2e5** [comment]
Actually you don't have to use a subdirectory to get the sorting right -- just use a character that comes after `.` in the ASCII table, like `_`.
