### ISSUE TITLE
Translation collaborators

### ISSUE THREAD

**Issue by noffle** [noffle/art-of-readme#41]
Hiya @qihaiyan @BrettDong @lennonjesus @jabiinfante! :wave: 

You've all been instrumental in volunteering your time to translate and review Art of README. You are all :star2:s!

Rather than me cc'ing you all on every revision PR, I wanted to ask if any of you would like push access to master to skip my (largely bureaucratic) rubber stamping on everything. You've all demonstrated excellent ability and judgment, and I'd :heart: to have you on the Art of README team!

Just reply here and I'll grant you access. :tada:  And if there's anyone else you'd like to suggest who I missed here, let me know that too!

*My requests*:

1. Feel free to merge changes to your `README*.md` of expertise at your discretion.
2. Follow the regular pull request process for changes to any other languages.
3. Keep on showing other volunteers the same compasion you've shown me by translating the article in the first place!

**Comment by qihaiyan** [comment]
Yes, i'am really glad to.
And i suggest invite @Artoria2e5 also to join the team, he's really professional.

**Comment by lennonjesus** [comment]
Thanks for inviting me, @noffle.

Challenge accepted. o/

**Comment by noffle** [comment]
@Artoria2e5 :wave: also extending the invitation to you if you're interested!

**Comment by Artoria2e5** [comment]
Hmm, why not.

**Comment by BrettDong** [comment]
Thanks for your invitation, but I believe the translation will be maintained well by @Artoria2e5 , @qihaiyan and @lennonjesus without me.

**Comment by noffle** [comment]
@Artoria2e5 invite sent! Thank you! :pray: 

@BrettDong I'm sure they're going to do a great job. :grinning:

**Comment by jabiinfante** [comment]
Sure! I'll try to keep it updated

**Comment by noffle** [comment]
@jabiinfante invite sent! Thanks everyone!
