### ISSUE TITLE
Chinese version update

### ISSUE THREAD

**Issue by lennonjesus** [noffle/art-of-readme#42]
Hei, @qihaiyan!

Can you review and complete the updates I made on [chinese-changes](https://github.com/noffle/art-of-readme/tree/chinese-changes) branch?

o/

**Comment by qihaiyan** [comment]
Hi, @lennonjesus 
I've completed the updates and fix some typo. I committed directly to the  chinese-changes branch.

**Comment by lennonjesus** [comment]
Thank you, @qihaiyan!
