### ISSUE TITLE
Inquiry about badges being too easy to abuse and selected example

### ISSUE THREAD

**Issue by jorgebucaran** [noffle/art-of-readme#57]
Howdy~! Love the idea of a README about READMEs, but was thrown off a bit by this comment about badges being easy to abuse.

<img width="464" alt="screen shot 2018-09-27 at 16 10 38" src="https://user-images.githubusercontent.com/56996/46128869-ea212800-c26f-11e8-83f8-ca2fe73dc9bb.png">

I agree, but I don't agree with the example that links to the Angular project's README. In fact, I think their README is quite examplary of good practice, short and simple, with just the necessary links to get you started.

<img width="982" alt="screen shot 2018-09-27 at 16 09 50" src="https://user-images.githubusercontent.com/56996/46128954-26548880-c270-11e8-8c16-fab584166d3b.png">

Now, compare their badge against defstream/nl3, which is selected as a good exemplar. It doesn't look exemplary to me. Does it look exemplary to you? Now, perhaps things changed since the last time you curated that list. It tends to happen.

<img width="982" alt="screen shot 2018-09-27 at 16 13 51" src="https://user-images.githubusercontent.com/56996/46129035-6156bc00-c270-11e8-99f8-7f3de121db4a.png">

Would you like switch the two links, find a different "bad" README example or perhaps just remove the link to the Angular project?

**Comment by noffle** [comment]
Agreed: nl3 has some serious badge-soup going on. I'm not sure how that ended up in the exemplar list. +1 on removing it.

I'm not a fan of angular's use of badges though either though. I've removed nl3 from the list -- thanks!
