### ISSUE TITLE
example of badge abuse

### ISSUE THREAD

**Issue by davidak** [noffle/art-of-readme#58]
[Here](https://github.com/noffle/art-of-readme/blame/b3d90dda4893f9ec7b0fe7383461ca3e567d0bbd/README.md#L338) you link to the angular repo as example of badge abuse.

Right now it looks quiet clean:

![screenshot from 2018-10-22 17-51-20](https://user-images.githubusercontent.com/91113/47302983-23f10e80-d623-11e8-91be-6e14f46d12e2.png)

Do you mean the CI badge or where there many more badges in the past? If so, you might want to link to a earlier commit which shows it.

A Ci badge also shows that **a CI is used**, which is professional. So it might be useful, even if the status if not relevant for users of the stable release.

You might find a better example with 2 rows of badges rendered on GitHub.

**Comment by noffle** [comment]
There are probably worse offenders, but angular's readme is pretty badge soup-y. I'm OK with keeping this example as-is. *Art of README* is an opinion piece! So it's OK if we disagree on this.
