### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by randomC0der** [noffle/art-of-readme#62]
Hello, is there any interest for a German translation?

**Comment by noffle** [comment]
@randomC0der I'm not sure, but if you write one I can merge it in.

**Comment by Ryuno-Ki** [comment]
Ah, cool. CC BY licensed.
I'll tackle the German translation after dinner!

**Comment by Ryuno-Ki** [comment]
First 20% in: https://github.com/noffle/art-of-readme/compare/master...Ryuno-Ki:ryuno-ki/de-de-translation
Will take a break here, since it's already evening.

**Comment by randomC0der** [comment]
@Ryuno-Ki Alright, I'll proofread it later when it's done

**Comment by noffle** [comment]
:tada:

**Comment by Ryuno-Ki** [comment]
@randomC0der Please check PR #63. Welcome a proofread!

**Comment by randomC0der** [comment]
I like the translation so far
