### ISSUE TITLE
Translating in French

### ISSUE THREAD

**Issue by Manfred-Madelaine-pro** [noffle/art-of-readme#64]
Hello Noffle,

I found your project on the "Art of README" very interesting and I would be interested in proposing a French version for all our French mates out there. What do you think ?

My brother @Ruben-Madelaine would also like to help.
Let me know if it would be of any interest to you.

Regards,

Manfred.

**Comment by noffle** [comment]
Hi @Manfred-Madelaine-pro, I'd be happy to merge a french translation if you & your brother feel like doing that work. :+1:

**Comment by Manfred-Madelaine-pro** [comment]
Great !

We started the translation: [FR translation (PR #65)](https://github.com/noffle/art-of-readme/pull/65).
Should be done in few days.

**Comment by randomC0der** [comment]
The pull request is merged, so this issue can be closed, right?

**Comment by noffle** [comment]
Yep!
